name: CI/CD Pipeline

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t myimage:${{ github.sha }} .

    - name: Run unittests
      run: docker run myimage:${{ github.sha }} python -m pytest .
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push Docker image
      if: ${{ success() }}


      run: |
        docker tag myimage:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/myimage:${{ github.sha }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/myimage:${{ github.sha }} 
    